### ISSUE TITLE
5/14 ToDo

### ISSUE THREAD

**Issue by ujkkk** [on-Haeya/pre-python-viz#1]
## 📝 Description
**무엇을?**
- 제한재 멘토님 멘토링
- 변수 시각화를 위한 공부 

**왜?**
- 적합한 프로젝트인지 확인

## ❗️Todo
- [x] 멘토님 인터뷰 질문 뽑기
- [x] 미팅 자료 정리
- [x] 인터프리터 공부
- [x] 어떻게 구현할지 생각

## ETC
기타사항

**Comment by ujkkk** [comment]
어떻게 구현할지 생각
--
**흐름**
1. 사용자 코드 입력 후 run
2. 전체 코드를 읽어와서 한 줄씩 해석 ex) x = a + B + (10*c)
3. '어휘 분석', 파서 통해 토큰화, ast 구조 만들기
4. 코드 의도에 맞는 의미 해석 ex) 10*c를 먼저 계산 후 a와 b값을 가져와서 더한 후 x에 대입하기
5. 프톤트가 애니메이션을 그릴 수 있는 정보 제공

🧐 **의문**
- 어떤 정보를 뽑아내야 하는거지? 
- 전체 코드 해석 후 한번에 결과를 보내주어도 문제가 없을까?
