### ISSUE TITLE
[Feat] 피연산자 3개 이상있는 표현식 파싱

### ISSUE THREAD

**Issue by ujkkk** [on-Haeya/pre-python-viz#13]
## 📝 Description
**무엇을?**
- 피연산자 3개 이상있는 표현식 파싱

## ❗️Todo
- [x] 전역 변수를 관리하는 기능 구현
- [x] 개수에 상관없이 파싱 가능하도록
- [x] 로드해야 할 변수 한 번에 찾기
- [x] 변수 실제 값을 표현식에 넣어 문자열 생성

## ETC
기타사항
