### ISSUE TITLE
[Feat] for문 파싱

### ISSUE THREAD

**Issue by SongGwanSeok** [on-Haeya/pre-python-viz#14]
## 📝 Description
**무엇을?**
- for문에 대한 부분을 해석해 시각화 json으로 변환

**왜?**
- for문을 시각화 하기 위해

## ❗️Todo
- [ ] for을 구별할 수 있는 요소 구현
- [ ] 조건에 대한 시각화
- [ ] for문 내부 로직에 대한 시각화

## ETC
기타사항
