### ISSUE TITLE
[Feat] 표현식 parsing과 단계별 결과 값 추출

### ISSUE THREAD

**Issue by ujkkk** [on-Haeya/pre-python-viz#8]
## 📝 Description
**무엇을?**
- 계산 수식, 변수 값 가져오기 포함된 표현식 적절히 파싱

## ❗️Todo
- [x] 구조 파악
- [x] 변수 값이 없는 계산식 파싱 (ex : 4+5*2)
- [x] 변수 값 로드 ( ex : a)
- [x] 변수 로드와 계산식 같이있는 표현식 파싱. ( ex :a=b+10)

## ETC
기타사항
